#!/usr/bin/php
<?php

require "vendor/autoload.php";
use PHPHtmlParser\Dom;

define('OUT_DIR', './data/');

$versions = ['oreo', 'pie', 'ten'];

// Map roms to a folder id on AFH
$map = [
         'du' => ['pie' => '272894', 'oreo' => '299956'],
         'aicp' => ['pie' => '287995'],
         'los' => ['ten' => '299960', 'pie' => '270857', 'oreo' => '299957'],
         'gzosp' => ['pie' => '291559'],
         'revenge' => ['pie' => '292955'],
         'aosip' => ['ten' => '299962', 'pie' => '294517'],
         'aosp' => ['ten' => '299294']
       ];

function generate($target, $afh, $ver)
{
	$url = "https://androidfilehost.com/?w=files&flid=$afh";
	echo "Scraping URL: $url".PHP_EOL;
	$dom = new Dom;
	$dom->loadFromUrl($url);
	if((int)$dom->rawSize > 0)
	{
		// Developer Name
		$dev = $dom->find('.developer-info');
		$a = $dev->find('a')[0];
		$developerName = $a->text;

		// Folder Name
		$dev = $dom->find('.folder-info');
		$h = $dev->find('h3')[0];
		$folderName = $h->text;

		// Files
		$roms = [];
		$files = $dom->find('.file');
		foreach ($files as $file)
		{
		    $rom = [];
		    if($link = $file->find('a')[0])
	            {
		    	$rom['filename'] = $link->text;
		    	$rom['url'] = "https://androidfilehost.com" . $link->getAttribute('href');
	
		    	$rom['downloads'] = $file->find('.file-attr-value')[0]->text;
		    	$rom['filesize'] = $file->find('.file-attr-value')[1]->text;
		    	$rom['date'] = $file->find('.file-attr-value')[2]->text;
	
	            	echo $rom['filename']."  ".$rom['date']."  DL:".$rom['downloads'].PHP_EOL;
		    	$roms[] = $rom;
	            }
		}

		$data = [];
		$data = ['rom' => $folderName, 'developer' => $developerName, 'data' => $roms];
		file_put_contents(OUT_DIR."/$ver/$target.json", json_encode($data));
	}
}

// If a rom name is specified on the command line
if(isset($argv[1]))
{
    $target = $argv[1];
    // Check that it's in the map
    if(in_array($target, array_keys($map)))
    {
        // Generate for this target
        foreach($map[$target] as $ver => $afh)
	{
	        generate($target, $afh, $ver);
	}
    }
    else
    {
        echo "ERROR: Unknown target.".PHP_EOL;
    }
}
else
{
    // Target not specified on the command line so generate them all
    foreach($map as $target => $afh)
    {
        generate($target, $afh);
    }
}
