#!/usr/bin/php
<?php

require "vendor/autoload.php";
use PHPHtmlParser\Dom;

define('OUT_DIR', './data/');

// Map roms to a folder id on AFH
$map = ['du' => '272894', 'aicp' => '287995', 'los' => '270857', 'gzosp' => '291559', 'revenge' => '292955'];

function generate($target, $afh)
{
	$dom = new Dom;
	$dom->loadFromUrl('https://androidfilehost.com/?w=files&flid='.$afh);

	// Developer Name
	$dev = $dom->find('.developer-info');
	$a = $dev->find('a')[0];
	$developerName = $a->text;

	// Folder Name
	$dev = $dom->find('.folder-info');
	$h = $dev->find('h3')[0];
	$folderName = $h->text;

	// Files
	$roms = [];
	$files = $dom->find('.file');
	foreach ($files as $file)
	{
	    $rom = [];

	    $link = $file->find('a')[0];
	    $rom['filename'] = $link->text;
	    $rom['url'] = "https://androidfilehost.com" . $link->getAttribute('href');

	    $rom['downloads'] = $file->find('.file-attr-value')[0]->text;
	    $rom['filesize'] = $file->find('.file-attr-value')[1]->text;
	    $rom['date'] = $file->find('.file-attr-value')[2]->text;

	    $roms[] = $rom;
	}

	$data = [];
	$data = ['rom' => $folderName, 'developer' => $developerName, 'data' => $roms];
	file_put_contents(OUT_DIR."/$target.json", json_encode($data));

}

// If a rom name is specified on the command line
if(isset($argv[1]))
{
    $target = $argv[1];
    // Check that it's in the map
    if(in_array($target, array_keys($map)))
    {
        // Generate for this target 
        generate($target, $map[$target]);
    }
    else
    {
        echo "ERROR: Unknown target.".PHP_EOL;
    }
}
else
{
    // Target not specified on the command line so generate them all
    foreach($map as $target => $afh)
    {
        generate($target, $afh);
    }
}